
CREATE TABLE productdb.SELLER (
SELLER_ID INT NOT NULL,
FIRST_NAME VARCHAR(25) NOT NULL,
LAST_NAME VARCHAR(25) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
CITY VARCHAR(50) NOT NULL,
STATE VARCHAR(50) NOT NULL,
PIN VARCHAR(5) NOT NULL,
PHONE VARCHAR(10) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
     PRIMARY KEY (SELLER_ID)
);

CREATE TABLE productdb.PRODUCT (
PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
SELLER_ID INT,
PRODUCT_NAME VARCHAR(100) NOT NULL,
SHORT_DESC VARCHAR(100) NOT NULL,
DETAILED_DESC VARCHAR(1000) NOT NULL,
CATEGORY VARCHAR(50) NOT NULL,
STARTING_PRICE int NOT NULL,
BID_ENDDATE DATE NOT NULL,
PRIMARY KEY (PRODUCT_ID),
FOREIGN KEY(SELLER_ID)
REFERENCES PRODUCTDB.SELLER(SELLER_ID)
ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE productdb.BUYER_BID (
BUYER_ID INT NOT NULL AUTO_INCREMENT,
PRODUCT_ID INT NOT NULL,
FIRST_NAME VARCHAR(25) NOT NULL,
LAST_NAME VARCHAR(25) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
CITY VARCHAR(50) NOT NULL,
STATE VARCHAR(50) NOT NULL,
PIN VARCHAR(5) NOT NULL,
PHONE VARCHAR(10) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
BID_AMOUNT INT NOT NULL,
PRIMARY KEY (BUYER_ID)
);

delete from productdb.seller;
drop table productdb.product;
drop table productdb.seller;
SELECT * FROM PRODUCTDB.SELLER
SELECT * FROM PRODUCTDB.PRODUCT
update productdb.seller set phone=1232267713 where seller_id=1

INSERT INTO productdb.SELLER (SELLER_ID,FIRST_NAME,LAST_NAME,ADDRESS,CITY,STATE,PIN,PHONE,EMAIL) 
VALUES (1001,"testfirstname","testlastname","test addres","test city","test state",12345,78547747,"test@gmail.com");


select last_insert_id();
update productdb.PRODUCT set SHORT_DESC='test desc' where seller_id=1 and product_id=1
SET SQL_SAFE_UPDATES=0;
delete from productdb.product where product_id=1
delete from productdb.seller where seller_id=1001